export interface PhotoManifestEntry {
  src?: string;
  path?: string;
  width: number;
  height: number;
  alt?: string;
  title?: string;
  description?: string;
}

export interface PhotoAlbumManifestEntry {
  slug: string;
  title: string;
  description: string;
  coverPhotoIndex?: number;
  photos: PhotoManifestEntry[];
}

// Generated by scripts/sync-photo-manifest-from-b2.mjs
// To regenerate: yarn sync:photos --albums=album-one,album-two
export const photoAlbumsManifest: PhotoAlbumManifestEntry[] = [
  {
    slug: "istanbul",
    title: "Istanbul",
    description: "",
    coverPhotoIndex: 0,
    photos: [
      {
        path: "istanbul/IMG_8263-HDR.jpg",
        width: 5686,
        height: 3791,
      },
      {
        path: "istanbul/IMG_8276.jpg",
        width: 2795,
        height: 4192,
      },
      {
        path: "istanbul/IMG_8282.jpg",
        width: 3670,
        height: 5505,
      },
      {
        path: "istanbul/IMG_8284.jpg",
        width: 4000,
        height: 6000,
      },
      {
        path: "istanbul/IMG_8293.jpg",
        width: 3727,
        height: 5591,
      },
      {
        path: "istanbul/IMG_8297.jpg",
        width: 5542,
        height: 3695,
      },
      {
        path: "istanbul/IMG_8304.jpg",
        width: 5320,
        height: 3547,
      },
      {
        path: "istanbul/IMG_8315.jpg",
        width: 5552,
        height: 3701,
      },
      {
        path: "istanbul/IMG_8319.jpg",
        width: 3791,
        height: 5687,
      },
      {
        path: "istanbul/IMG_8325.jpg",
        width: 3330,
        height: 4995,
      },
      {
        path: "istanbul/IMG_8346.jpg",
        width: 5580,
        height: 3720,
      },
      {
        path: "istanbul/IMG_8348.jpg",
        width: 5749,
        height: 3833,
      },
      {
        path: "istanbul/IMG_8355.jpg",
        width: 3456,
        height: 5184,
      },
      {
        path: "istanbul/IMG_8359.jpg",
        width: 5167,
        height: 3445,
      },
      {
        path: "istanbul/IMG_8364.jpg",
        width: 3945,
        height: 5918,
      },
      {
        path: "istanbul/IMG_8378.jpg",
        width: 6000,
        height: 4000,
      },
      {
        path: "istanbul/IMG_8384.jpg",
        width: 5344,
        height: 3563,
      },
      {
        path: "istanbul/IMG_8386.jpg",
        width: 3640,
        height: 5460,
      },
      {
        path: "istanbul/IMG_8390.jpg",
        width: 3317,
        height: 4976,
      },
      {
        path: "istanbul/IMG_8393.jpg",
        width: 3819,
        height: 5729,
      },
      {
        path: "istanbul/IMG_8395.jpg",
        width: 3856,
        height: 5784,
      },
      {
        path: "istanbul/IMG_8402.jpg",
        width: 5096,
        height: 3397,
      },
      {
        path: "istanbul/IMG_8403.jpg",
        width: 4990,
        height: 3327,
      },
      {
        path: "istanbul/IMG_8404.jpg",
        width: 5136,
        height: 3424,
      },
      {
        path: "istanbul/IMG_8414.jpg",
        width: 4000,
        height: 6000,
      },
      {
        path: "istanbul/IMG_8418.jpg",
        width: 3325,
        height: 4987,
      },
      {
        path: "istanbul/IMG_8429.jpg",
        width: 5199,
        height: 3466,
      },
      {
        path: "istanbul/IMG_8432.jpg",
        width: 3583,
        height: 5375,
      },
      {
        path: "istanbul/IMG_8442-Enhanced-NR.jpg",
        width: 2477,
        height: 3716,
      },
      {
        path: "istanbul/IMG_8445.jpg",
        width: 3373,
        height: 5059,
      },
      {
        path: "istanbul/IMG_8451.jpg",
        width: 3770,
        height: 5655,
      },
      {
        path: "istanbul/IMG_8453.jpg",
        width: 3788,
        height: 5682,
      },
      {
        path: "istanbul/IMG_8468.jpg",
        width: 3762,
        height: 5643,
      },
      {
        path: "istanbul/IMG_8470.jpg",
        width: 5489,
        height: 3659,
      },
      {
        path: "istanbul/IMG_8474.jpg",
        width: 4796,
        height: 3197,
      },
      {
        path: "istanbul/IMG_8477.jpg",
        width: 5258,
        height: 3505,
      },
      {
        path: "istanbul/IMG_8485.jpg",
        width: 3837,
        height: 5755,
      },
      {
        path: "istanbul/IMG_8489.jpg",
        width: 6000,
        height: 4000,
      },
      {
        path: "istanbul/IMG_8505.jpg",
        width: 3549,
        height: 5324,
      },
      {
        path: "istanbul/IMG_8521-Enhanced-NR.jpg",
        width: 4000,
        height: 6000,
      },
      {
        path: "istanbul/IMG_8528.jpg",
        width: 5447,
        height: 3631,
      },
      {
        path: "istanbul/IMG_8536.jpg",
        width: 5731,
        height: 3821,
      },
      {
        path: "istanbul/IMG_8538.jpg",
        width: 5852,
        height: 3901,
      },
      {
        path: "istanbul/IMG_8541.jpg",
        width: 6000,
        height: 4000,
      },
      {
        path: "istanbul/IMG_8550.jpg",
        width: 2519,
        height: 3779,
      },
      {
        path: "istanbul/IMG_8553.jpg",
        width: 5393,
        height: 3595,
      },
      {
        path: "istanbul/IMG_8559.jpg",
        width: 5421,
        height: 3614,
      },
      {
        path: "istanbul/IMG_8570.jpg",
        width: 3959,
        height: 5938,
      },
      {
        path: "istanbul/IMG_8575.jpg",
        width: 6000,
        height: 4000,
      },
      {
        path: "istanbul/IMG_8579.jpg",
        width: 5364,
        height: 3576,
      },
      {
        path: "istanbul/IMG_8585.jpg",
        width: 5806,
        height: 3871,
      },
      {
        path: "istanbul/IMG_8588.jpg",
        width: 6000,
        height: 4000,
      },
      {
        path: "istanbul/IMG_8595.jpg",
        width: 4632,
        height: 3088,
      },
      {
        path: "istanbul/IMG_8597.jpg",
        width: 5725,
        height: 3817,
      },
      {
        path: "istanbul/IMG_8600.jpg",
        width: 5474,
        height: 3649,
      },
      {
        path: "istanbul/IMG_8605.jpg",
        width: 5774,
        height: 3849,
      },
      {
        path: "istanbul/IMG_8608.jpg",
        width: 3315,
        height: 4972,
      },
      {
        path: "istanbul/IMG_8610.jpg",
        width: 2646,
        height: 3969,
      },
      {
        path: "istanbul/IMG_8614.jpg",
        width: 3749,
        height: 5623,
      },
      {
        path: "istanbul/IMG_8619.jpg",
        width: 4960,
        height: 3307,
      },
      {
        path: "istanbul/IMG_8622-Enhanced-NR.jpg",
        width: 5791,
        height: 3861,
      },
      {
        path: "istanbul/IMG_8624-Enhanced-NR.jpg",
        width: 3597,
        height: 5395,
      },
      {
        path: "istanbul/IMG_8625.jpg",
        width: 5381,
        height: 3587,
      },
      {
        path: "istanbul/IMG_8626-Enhanced-NR.jpg",
        width: 3729,
        height: 5593,
      },
      {
        path: "istanbul/IMG_8631.jpg",
        width: 3445,
        height: 5168,
      },
      {
        path: "istanbul/IMG_8637.jpg",
        width: 3364,
        height: 5046,
      },
      {
        path: "istanbul/IMG_8646.jpg",
        width: 5090,
        height: 3393,
      },
      {
        path: "istanbul/IMG_8650.jpg",
        width: 5356,
        height: 3571,
      },
      {
        path: "istanbul/IMG_8652.jpg",
        width: 3600,
        height: 5400,
      },
      {
        path: "istanbul/IMG_8659.jpg",
        width: 4000,
        height: 6000,
      },
      {
        path: "istanbul/IMG_8663.jpg",
        width: 3423,
        height: 5135,
      },
      {
        path: "istanbul/IMG_8679.jpg",
        width: 5464,
        height: 3643,
      },
      {
        path: "istanbul/IMG_8680.jpg",
        width: 5516,
        height: 3677,
      },
      {
        path: "istanbul/IMG_8683.jpg",
        width: 5727,
        height: 3818,
      },
      {
        path: "istanbul/IMG_8686-Enhanced-NR.jpg",
        width: 3032,
        height: 4548,
      },
      {
        path: "istanbul/IMG_8696.jpg",
        width: 6000,
        height: 4000,
      },
      {
        path: "istanbul/IMG_8700.jpg",
        width: 3749,
        height: 5623,
      },
      {
        path: "istanbul/IMG_8703.jpg",
        width: 3509,
        height: 5263,
      },
      {
        path: "istanbul/IMG_8712.jpg",
        width: 3809,
        height: 5713,
      },
      {
        path: "istanbul/IMG_8714.jpg",
        width: 5059,
        height: 3373,
      },
      {
        path: "istanbul/IMG_8721.jpg",
        width: 3049,
        height: 4574,
      },
      {
        path: "istanbul/IMG_8726-Enhanced-NR.jpg",
        width: 5506,
        height: 3671,
      },
    ],
  },
  {
    slug: "dolomites",
    title: "Dolomites",
    description: "",
    coverPhotoIndex: 0,
    photos: [
      {
        path: "dolomites/DJI_0009.jpg",
        width: 5207,
        height: 1949,
      },
      {
        path: "dolomites/DJI_0012-HDR.jpg",
        width: 4449,
        height: 2964,
      },
      {
        path: "dolomites/DJI_0060-HDR.jpg",
        width: 5373,
        height: 3579,
      },
      {
        path: "dolomites/DJI_0128-HDR-2.jpg",
        width: 4885,
        height: 3254,
      },
      {
        path: "dolomites/DJI_0147-HDR.jpg",
        width: 4851,
        height: 3232,
      },
      {
        path: "dolomites/DJI_0173-HDR.jpg",
        width: 4452,
        height: 2966,
      },
      {
        path: "dolomites/IMG_4403.jpg",
        width: 2757,
        height: 2068,
      },
      {
        path: "dolomites/IMG_4458.jpg",
        width: 3011,
        height: 2258,
      },
      {
        path: "dolomites/IMG_4564.jpg",
        width: 3414,
        height: 2560,
      },
      {
        path: "dolomites/IMG_4688.jpg",
        width: 4032,
        height: 3024,
      },
      {
        path: "dolomites/IMG_4704.jpg",
        width: 2754,
        height: 3672,
      },
      {
        path: "dolomites/IMG_4718.jpg",
        width: 3586,
        height: 2690,
      },
      {
        path: "dolomites/IMG_4725.jpg",
        width: 3634,
        height: 2726,
      },
      {
        path: "dolomites/IMG_4780.jpg",
        width: 3572,
        height: 2679,
      },
      {
        path: "dolomites/IMG_4796.jpg",
        width: 3765,
        height: 2824,
      },
      {
        path: "dolomites/IMG_4971.jpg",
        width: 3189,
        height: 2392,
      },
      {
        path: "dolomites/IMG_4990.jpg",
        width: 3262,
        height: 2447,
      },
      {
        path: "dolomites/IMG_5001.jpg",
        width: 3105,
        height: 2329,
      },
      {
        path: "dolomites/IMG_5019.jpg",
        width: 3090,
        height: 2318,
      },
      {
        path: "dolomites/IMG_5051.jpg",
        width: 3807,
        height: 2855,
      },
      {
        path: "dolomites/IMG_5066.jpg",
        width: 3435,
        height: 2576,
      },
      {
        path: "dolomites/IMG_5106.jpg",
        width: 3468,
        height: 2601,
      },
      {
        path: "dolomites/IMG_5389.jpg",
        width: 4061,
        height: 2707,
      },
      {
        path: "dolomites/IMG_5463.jpg",
        width: 5874,
        height: 3916,
      },
      {
        path: "dolomites/IMG_5512.jpg",
        width: 3559,
        height: 5339,
      },
      {
        path: "dolomites/IMG_5569.jpg",
        width: 4000,
        height: 6000,
      },
      {
        path: "dolomites/IMG_5600.jpg",
        width: 5808,
        height: 3872,
      },
      {
        path: "dolomites/IMG_5643.jpg",
        width: 4999,
        height: 3333,
      },
      {
        path: "dolomites/IMG_5714.jpg",
        width: 4670,
        height: 3113,
      },
      {
        path: "dolomites/IMG_5720.jpg",
        width: 5595,
        height: 3730,
      },
      {
        path: "dolomites/IMG_5741.jpg",
        width: 5251,
        height: 3501,
      },
    ],
  },
];
